import express from "express";
import upload from "../middleware/multer.js";
import { getMe, logIn, logOut, signUp } from "../controller/authController.js";
import { jwtVerify } from "../middleware/jwtVerify.js";
const userRouter = express.Router();
userRouter.post("/signup", upload.single("image"), signUp);
userRouter.post("/login", logIn);
userRouter.post("/logout", logOut);
userRouter.get("/me", jwtVerify, getMe);
export default userRouter;
